package app.futrue.commons.bean;

import app.futrue.commons.base.PageModel;

public class Brand {
	
	/**
	 * 
	 */
	private PageModel model;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_brand.brand_id
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    private Short brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_brand.brand_name
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_brand.brand_logo
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    private String brandLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_brand.site_url
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    private String siteUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_brand.sort_order
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    private Byte sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_brand.is_show
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    private Boolean isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_brand.brand_desc
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    private String brandDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_brand.brand_id
     *
     * @return the value of ecs_brand.brand_id
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public Short getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_brand.brand_id
     *
     * @param brandId the value for ecs_brand.brand_id
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public void setBrandId(Short brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_brand.brand_name
     *
     * @return the value of ecs_brand.brand_name
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_brand.brand_name
     *
     * @param brandName the value for ecs_brand.brand_name
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_brand.brand_logo
     *
     * @return the value of ecs_brand.brand_logo
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public String getBrandLogo() {
        return brandLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_brand.brand_logo
     *
     * @param brandLogo the value for ecs_brand.brand_logo
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public void setBrandLogo(String brandLogo) {
        this.brandLogo = brandLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_brand.site_url
     *
     * @return the value of ecs_brand.site_url
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public String getSiteUrl() {
        return siteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_brand.site_url
     *
     * @param siteUrl the value for ecs_brand.site_url
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public void setSiteUrl(String siteUrl) {
        this.siteUrl = siteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_brand.sort_order
     *
     * @return the value of ecs_brand.sort_order
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public Byte getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_brand.sort_order
     *
     * @param sortOrder the value for ecs_brand.sort_order
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public void setSortOrder(Byte sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_brand.is_show
     *
     * @return the value of ecs_brand.is_show
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_brand.is_show
     *
     * @param isShow the value for ecs_brand.is_show
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_brand.brand_desc
     *
     * @return the value of ecs_brand.brand_desc
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public String getBrandDesc() {
        return brandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_brand.brand_desc
     *
     * @param brandDesc the value for ecs_brand.brand_desc
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    public void setBrandDesc(String brandDesc) {
        this.brandDesc = brandDesc;
    }

	public PageModel getModel() {
		return model;
	}

	public void setModel(PageModel model) {
		this.model = model;
	}
}