package app.future.server.dao;

import app.future.commons.bean.Card;

import java.util.List;

public interface CardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    int deleteByPrimaryKey(Short cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    int insertSelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    Card selectByPrimaryKey(Short cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    int updateByPrimaryKeySelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    int updateByPrimaryKey(Card record);

	List<Card> find(Card bean);

	Long findTotal(Card bean);
}