package app.future.server.dao;

import app.future.commons.base.BaseMapper;
import app.future.commons.bean.Card;

public interface CardMapper extends BaseMapper<Card>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    int deleteByPrimaryKey(Short cardId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbggenerated Sat Nov 29 13:54:12 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(Card record);

}